
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "../components/Navbar";
import HeroSection from "@/components/HeroSection";
import AboutSection from "@/components/AboutSection";
import { VortexDemoSecond } from "@/components/VortexDemoSecond";
import { BentoGridDemo } from "@/components/BentoGridDemo";
import { AuroraBackgroundDemo } from "@/components/AuroraBackgroundDemo";
import MansoryGrid from "@/components/MansoryGrid";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Elesium Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <AuroraBackgroundDemo/>
        <NavbarDemo/>
        <HeroSection/>
        
        <BentoGridDemo/>
        <MansoryGrid/>
      </body>
    </html>
  );
}
